# Exercícios de Pandas (50)

Este notebook foi criado para prática. Os exercícios vão do básico ao avançado.

Antes de começar:
```python
import pandas as pd
import numpy as np
```

## Dataset sugerido

Você pode usar qualquer CSV com colunas semelhantes às abaixo:
`id, nome, idade, cidade, estado, salario, departamento, data_admissao, vendas`

Ou criar um DataFrame próprio.

## Básico

In [1]:
import pandas as pd
import numpy as np

### Exercício 1
**Enunciado:** Carregue um arquivo CSV em um DataFrame.

In [100]:
df = pd.read_csv('funcionarios_vendas.csv')

### Exercício 2
**Enunciado:** Exiba as cinco primeiras linhas.

In [5]:
# Sua solução aqui
df.head()

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
0,1,Ana,53,Recife,PE,TI,8578.0,462465,NaN,2024-02-16
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
2,3,Samuel,48,Brasília,DF,Financeiro,2852.0,272900,4.9,2019-12-02
3,4,Juliana,23,Recife,PE,RH,11594.0,461227,3.0,2020-03-08
4,5,Carlos,19,Belo Horizonte,MG,TI,16143.0,298522,1.6,2025-03-19

### Exercício 3
**Enunciado:** Exiba as cinco últimas linhas.

In [6]:
# Sua solução aqui
df.tail()

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
505,486,Bruno,64,Salvador,BA,TI,16552.0,145643,1.7,2020-03-05
506,311,Olivia,54,Fortaleza,CE,Marketing,7260.0,256553,4.5,2023-07-13
507,32,Nicolas,43,São Paulo,SP,Financeiro,13074.0,310748,3.2,2023-02-20
508,250,Mariana,39,Belo Horizonte,MG,TI,5730.0,358918,4.9,2023-08-16
509,91,Vinicius,21,Fortaleza,CE,Operações,8043.0,389954,3.0,2019-06-11

### Exercício 4
**Enunciado:** Mostre o formato do DataFrame.

In [7]:
# Sua solução aqui
type(df)

pandas.core.frame.DataFrame

### Exercício 5
**Enunciado:** Liste os nomes das colunas.

In [8]:
# Sua solução aqui
df.columns

Index(['id', 'nome', 'idade', 'cidade', 'estado', 'departamento', 'salario',
       'vendas', 'avaliacao', 'data_admissao'],
      dtype='object')

### Exercício 6
**Enunciado:** Mostre os tipos de dados.

In [9]:
# Sua solução aqui
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             510 non-null    int64
 1   nome           510 non-null    object
 2   idade          510 non-null    int64
 3   cidade         510 non-null    object
 4   estado         510 non-null    object
 5   departamento   510 non-null    object
 6   salario        495 non-null    float64
 7   vendas         510 non-null    int64
 8   avaliacao      495 non-null    float64
 9   data_admissao  510 non-null    object
dtypes: float64(2), int64(3), object(5)
memory usage: 40.0+ KB

### Exercício 7
**Enunciado:** Obtenha estatísticas descritivas.

In [10]:
# Sua solução aqui
df.describe()

               id       idade       salario         vendas   avaliacao
count  510.000000  510.000000    495.000000     510.000000  495.000000
mean   250.317647   41.331373  10348.650505  242518.084314    3.016970
std    144.900579   13.816863   4447.126862  146220.200650    1.175386
min      1.000000   18.000000   2501.000000    3191.000000    1.000000
25%    124.250000   29.000000   6630.000000  119026.250000    1.900000
50%    250.500000   42.000000  10404.000000  225420.000000    3.100000
75%    374.750000   53.000000  14227.500000  370682.250000    4.000000
max    500.000000   65.000000  17976.000000  499499.000000    5.000000

### Exercício 8
**Enunciado:** Conte quantos valores nulos existem por coluna.

In [28]:
for i in df.columns:
    print(f"Coluna '{i}': {df[i].isnull().sum()} valores nulos")

Coluna 'id': 0 valores nulos
Coluna 'nome': 0 valores nulos
Coluna 'idade': 0 valores nulos
Coluna 'cidade': 0 valores nulos
Coluna 'estado': 0 valores nulos
Coluna 'departamento': 0 valores nulos
Coluna 'salario': 15 valores nulos
Coluna 'vendas': 0 valores nulos
Coluna 'avaliacao': 15 valores nulos
Coluna 'data_admissao': 0 valores nulos

### Exercício 9
**Enunciado:** Renomeie uma coluna.

In [39]:
# Sua solução aqui
df = df.rename(columns={'nome': 'Nome_Completo'})
df.columns

Index(['id', 'Nome_Completo', 'idade', 'cidade', 'estado', 'departamento',
       'salario', 'vendas', 'avaliacao', 'data_admissao'],
      dtype='object')

In [40]:
df = df.rename(columns={'Nome_Completo': 'nome'})
df.columns

Index(['id', 'nome', 'idade', 'cidade', 'estado', 'departamento', 'salario',
       'vendas', 'avaliacao', 'data_admissao'],
      dtype='object')

### Exercício 10
**Enunciado:** Selecione apenas duas colunas.

In [46]:
# Sua solução aqui
df[['nome', 'vendas']]

         nome  vendas
0         Ana  462465
1      Carlos  201659
2      Samuel  272900
3     Juliana  461227
4      Carlos  298522
..        ...     ...
505     Bruno  145643
506    Olivia  256553
507   Nicolas  310748
508   Mariana  358918
509  Vinicius  389954

[510 rows x 2 columns]

## Seleção e Filtros

### Exercício 11
**Enunciado:** Filtre pessoas com idade maior que 30.

In [48]:
# Sua solução aqui
df[df['idade'] > 30]

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
0,1,Ana,53,Recife,PE,TI,8578.0,462465,NaN,2024-02-16
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
2,3,Samuel,48,Brasília,DF,Financeiro,2852.0,272900,4.9,2019-12-02
5,6,Helena,37,Fortaleza,CE,Vendas,14580.0,135327,2.4,2020-12-24
6,7,Nicolas,45,Brasília,DF,Marketing,9505.0,407700,2.7,2022-05-13
...,...,...,...,...,...,...,...,...,...,...
501,341,Daniela,36,Belo Horizonte,MG,Marketing,6646.0,180302,4.9,2024-12-03
505,486,Bruno,64,Salvador,BA,TI,16552.0,145643,1.7,2020-03-05
506,311,Olivia,54,Fortaleza,CE,Marketing,7260.0,256553,4.5,2023-07-13
507,32,Nicolas,43,São Paulo,SP,Financeiro,13074.0,310748,3.2,2023-02-20
508,250,Mariana,39,Belo Horizonte,MG,TI,5730.0,358918,4.9,2023-08-16

### Exercício 12
**Enunciado:** Filtre salários acima da média.

In [51]:
# Sua solução aqui
media = df['salario'].mean()
df[df['salario'] > media]

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
3,4,Juliana,23,Recife,PE,RH,11594.0,461227,3.0,2020-03-08
4,5,Carlos,19,Belo Horizonte,MG,TI,16143.0,298522,1.6,2025-03-19
5,6,Helena,37,Fortaleza,CE,Vendas,14580.0,135327,2.4,2020-12-24
7,8,Samuel,28,Brasília,DF,TI,16536.0,125703,4.0,2020-01-01
...,...,...,...,...,...,...,...,...,...,...
495,496,Igor,54,Recife,PE,TI,13738.0,356124,NaN,2021-06-20
499,500,Eduardo,42,Curitiba,PR,Marketing,17663.0,64028,1.9,2018-06-10
504,480,Tatiane,29,Curitiba,PR,Financeiro,17123.0,341895,4.6,2020-10-12
505,486,Bruno,64,Salvador,BA,TI,16552.0,145643,1.7,2020-03-05
507,32,Nicolas,43,São Paulo,SP,Financeiro,13074.0,310748,3.2,2023-02-20

### Exercício 13
**Enunciado:** Selecione registros de uma cidade específica.

In [54]:
# Sua solução aqui
df[df['cidade'] == 'Curitiba']

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
16,17,Karina,25,Curitiba,PR,Vendas,12079.0,229189,1.6,2018-11-19
24,25,Daniela,36,Curitiba,PR,RH,9063.0,315507,3.6,2024-11-17
29,30,Nicolas,64,Curitiba,PR,Operações,14503.0,454179,3.8,2016-12-25
32,33,Lucas,31,Curitiba,PR,Financeiro,12133.0,272670,3.1,2023-06-12
...,...,...,...,...,...,...,...,...,...,...
480,481,Juliana,36,Curitiba,PR,Marketing,11882.0,98605,3.4,2020-08-02
487,488,Fernanda,33,Curitiba,PR,TI,10343.0,260298,4.0,2023-12-28
497,498,Tatiane,23,Curitiba,PR,RH,4304.0,85457,4.6,2019-06-13
499,500,Eduardo,42,Curitiba,PR,Marketing,17663.0,64028,1.9,2018-06-10
504,480,Tatiane,29,Curitiba,PR,Financeiro,17123.0,341895,4.6,2020-10-12

### Exercício 14
**Enunciado:** Filtre usando duas condições.

In [57]:
# Sua solução aqui
df[(df['cidade'] == 'Curitiba') & (df['vendas'] > 1000)]

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
16,17,Karina,25,Curitiba,PR,Vendas,12079.0,229189,1.6,2018-11-19
24,25,Daniela,36,Curitiba,PR,RH,9063.0,315507,3.6,2024-11-17
29,30,Nicolas,64,Curitiba,PR,Operações,14503.0,454179,3.8,2016-12-25
32,33,Lucas,31,Curitiba,PR,Financeiro,12133.0,272670,3.1,2023-06-12
...,...,...,...,...,...,...,...,...,...,...
480,481,Juliana,36,Curitiba,PR,Marketing,11882.0,98605,3.4,2020-08-02
487,488,Fernanda,33,Curitiba,PR,TI,10343.0,260298,4.0,2023-12-28
497,498,Tatiane,23,Curitiba,PR,RH,4304.0,85457,4.6,2019-06-13
499,500,Eduardo,42,Curitiba,PR,Marketing,17663.0,64028,1.9,2018-06-10
504,480,Tatiane,29,Curitiba,PR,Financeiro,17123.0,341895,4.6,2020-10-12

### Exercício 15
**Enunciado:** Ordene por salário crescente.

In [59]:
# Sua solução aqui
df.sort_values('salario', ascending=False)

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
26,27,Vinicius,50,Salvador,BA,RH,17976.0,131733,4.0,2018-11-30
172,173,Mariana,55,Belo Horizonte,MG,TI,17898.0,40108,3.7,2016-06-13
147,148,Mariana,53,Belo Horizonte,MG,RH,17860.0,118947,4.1,2020-04-05
22,23,Mariana,43,Rio de Janeiro,RJ,Operações,17782.0,256353,1.8,2022-02-20
400,401,Paulo,55,Fortaleza,CE,RH,17722.0,254311,3.7,2020-02-03
...,...,...,...,...,...,...,...,...,...,...
359,360,Nicolas,47,Belo Horizonte,MG,Marketing,NaN,429440,1.3,2025-01-15
375,376,Ana,31,Curitiba,PR,Vendas,NaN,201139,4.2,2016-07-01
395,396,Karina,35,Curitiba,PR,Vendas,NaN,371931,1.7,2018-11-19
432,433,Renata,46,Brasília,DF,TI,NaN,9503,NaN,2019-03-26
498,499,Helena,25,São Paulo,SP,Marketing,NaN,144129,4.2,2018-05-22

### Exercício 16
**Enunciado:** Ordene por idade decrescente.

In [61]:
# Sua solução aqui
df.sort_values('idade', ascending=False)

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
330,331,Juliana,65,São Paulo,SP,RH,17454.0,122811,1.5,2019-02-20
339,340,Mariana,65,Curitiba,PR,TI,11406.0,154544,3.8,2025-05-22
193,194,Gabriel,65,Recife,PE,Marketing,12056.0,234555,1.4,2020-02-19
505,486,Bruno,64,Salvador,BA,TI,16552.0,145643,1.7,2020-03-05
448,449,Olivia,64,Recife,PE,Financeiro,3487.0,317563,1.7,2016-07-16
...,...,...,...,...,...,...,...,...,...,...
73,74,Paulo,18,Rio de Janeiro,RJ,Financeiro,7099.0,10699,4.0,2018-11-20
464,465,Daniela,18,Curitiba,PR,Financeiro,14421.0,77794,4.5,2016-01-23
429,430,Daniela,18,Curitiba,PR,Operações,9500.0,39071,4.4,2024-03-06
30,31,Paulo,18,Brasília,DF,RH,13317.0,42828,2.5,2024-08-12
52,53,Fernanda,18,Belo Horizonte,MG,TI,12839.0,102747,1.7,2025-08-16

### Exercício 17
**Enunciado:** Selecione as 10 maiores vendas.

In [62]:
# Sua solução aqui
df[['nome', 'vendas']].sort_values('vendas', ascending=False).head(10)

        nome  vendas
11     Bruno  499499
14       Ana  498946
476   Helena  498685
349   Samuel  498603
256  Mariana  497660
377  Juliana  497030
238  Gabriel  496037
204    Lucas  495370
12    Renata  493948
228  Gabriel  493158

### Exercício 18
**Enunciado:** Use isin para filtrar departamentos.

In [67]:
# Sua solução aqui
df[df['cidade'].isin(['Curitiba', 'São Paulo'])]

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
16,17,Karina,25,Curitiba,PR,Vendas,12079.0,229189,1.6,2018-11-19
24,25,Daniela,36,Curitiba,PR,RH,9063.0,315507,3.6,2024-11-17
29,30,Nicolas,64,Curitiba,PR,Operações,14503.0,454179,3.8,2016-12-25
31,32,Nicolas,43,São Paulo,SP,Financeiro,13074.0,310748,3.2,2023-02-20
...,...,...,...,...,...,...,...,...,...,...
498,499,Helena,25,São Paulo,SP,Marketing,NaN,144129,4.2,2018-05-22
499,500,Eduardo,42,Curitiba,PR,Marketing,17663.0,64028,1.9,2018-06-10
503,68,Igor,28,São Paulo,SP,Vendas,4865.0,258503,3.4,2019-11-16
504,480,Tatiane,29,Curitiba,PR,Financeiro,17123.0,341895,4.6,2020-10-12
507,32,Nicolas,43,São Paulo,SP,Financeiro,13074.0,310748,3.2,2023-02-20

### Exercício 19
**Enunciado:** Filtre datas após um determinado ano.

In [68]:
# Sua solução aqui
df[df['data_admissao'] > '2020-01-01']

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
0,1,Ana,53,Recife,PE,TI,8578.0,462465,NaN,2024-02-16
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
3,4,Juliana,23,Recife,PE,RH,11594.0,461227,3.0,2020-03-08
4,5,Carlos,19,Belo Horizonte,MG,TI,16143.0,298522,1.6,2025-03-19
5,6,Helena,37,Fortaleza,CE,Vendas,14580.0,135327,2.4,2020-12-24
...,...,...,...,...,...,...,...,...,...,...
504,480,Tatiane,29,Curitiba,PR,Financeiro,17123.0,341895,4.6,2020-10-12
505,486,Bruno,64,Salvador,BA,TI,16552.0,145643,1.7,2020-03-05
506,311,Olivia,54,Fortaleza,CE,Marketing,7260.0,256553,4.5,2023-07-13
507,32,Nicolas,43,São Paulo,SP,Financeiro,13074.0,310748,3.2,2023-02-20
508,250,Mariana,39,Belo Horizonte,MG,TI,5730.0,358918,4.9,2023-08-16

### Exercício 20
**Enunciado:** Crie uma nova coluna baseada em uma condição.

In [69]:
# Sua solução aqui
df['target'] = np.where(df['vendas'] > 1000, 1, 0)

## Limpeza de Dados

### Exercício 21
**Enunciado:** Remova linhas duplicadas.

In [74]:
# Sua solução aqui
df = df.drop_duplicates()

### Exercício 22
**Enunciado:** Preencha valores nulos com a média.

In [79]:
# Sua solução aqui

# Seleciona apenas colunas numéricas
num_cols = df.select_dtypes(include=["int64", "float64"]).columns

# Preenche os nulos com a média de cada coluna
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

### Exercício 23
**Enunciado:** Preencha valores categóricos nulos.

In [ ]:
# Sua solução aqui

# Seleciona apenas colunas categóricas
cat_cols = df.select_dtypes(include=["object", "category"]).columns

# Preenche os nulos com a moda de cada coluna
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

### Exercício 24
**Enunciado:** Remova linhas com valores nulos.

In [91]:
# Sua solução aqui
df.dropna(inplace=True)

### Exercício 25
**Enunciado:** Converta uma coluna para datetime.

In [93]:
# Sua solução aqui
df['data_admissao'] = pd.to_datetime(df['data_admissao'])

### Exercício 26
**Enunciado:** Converta uma coluna para categoria.

In [94]:
# Sua solução aqui
df['nome'] = df['nome'].astype('category')

### Exercício 27
**Enunciado:** Padronize textos para maiúsculas.

In [96]:
# Sua solução aqui
df['nome'] = df['nome'].str.upper()
df.head()

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
1,2,CARLOS,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
2,3,SAMUEL,48,Brasília,DF,Financeiro,2852.0,272900,4.9,2019-12-02
3,4,JULIANA,23,Recife,PE,RH,11594.0,461227,3.0,2020-03-08
4,5,CARLOS,19,Belo Horizonte,MG,TI,16143.0,298522,1.6,2025-03-19
5,6,HELENA,37,Fortaleza,CE,Vendas,14580.0,135327,2.4,2020-12-24

### Exercício 28
**Enunciado:** Remova espaços extras em strings.

In [103]:
# Tira os espaços em branco do início e do fim da string na coluna 'cidade'
df['cidade'] = df['cidade'].str.strip()
df.head()

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
0,1,Ana,53,Recife,PE,TI,8578.0,462465,NaN,2024-02-16
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
2,3,Samuel,48,Brasília,DF,Financeiro,2852.0,272900,4.9,2019-12-02
3,4,Juliana,23,Recife,PE,RH,11594.0,461227,3.0,2020-03-08
4,5,Carlos,19,Belo Horizonte,MG,TI,16143.0,298522,1.6,2025-03-19

In [107]:
# Tira todos os espaços da coluna
df['cidade'] = df['cidade'].str.replace(' ', '', regex=False)
df.head()

,id,nome,idade,cidade,estado,departamento,salario,vendas,avaliacao,data_admissao
0,1,Ana,53,Recife,PE,TI,8578.0,462465,NaN,2024-02-16
1,2,Carlos,41,Curitiba,PR,Vendas,16018.0,201659,1.4,2025-03-04
2,3,Samuel,48,Brasília,DF,Financeiro,2852.0,272900,4.9,2019-12-02
3,4,Juliana,23,Recife,PE,RH,11594.0,461227,3.0,2020-03-08
4,5,Carlos,19,BeloHorizonte,MG,TI,16143.0,298522,1.6,2025-03-19

### Exercício 29
**Enunciado:** Substitua valores específicos.

Empty DataFrame
Columns: [id, nome, idade, cidade, estado, departamento, salario, vendas, avaliacao, data_admissao]
Index: []

### Exercício 30
**Enunciado:** Identifique outliers usando IQR.

In [115]:
# Seleciona colunas numéricas
num_cols = df.select_dtypes(include='number').columns

# Máscara para identificar linhas com outliers
mask_outliers = pd.Series(False, index=df.index)

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR

    mask_outliers |= (
        (df[col] < limite_inferior) |
        (df[col] > limite_superior)
    )

# DataFrame contendo apenas os outliers
outliers = df[mask_outliers]

print(outliers)

Empty DataFrame
Columns: [id, nome, idade, cidade, estado, departamento, salario, vendas, avaliacao, data_admissao]
Index: []

## Agrupamentos

### Exercício 31
**Enunciado:** Agrupe por departamento.

In [117]:
# Sua solução aqui
df.groupby('departamento')['vendas'].sum()

departamento
Financeiro    21176982
Marketing     19878605
Operações     20564946
RH            20278738
TI            22520523
Vendas        19264429
Name: vendas, dtype: int64

### Exercício 32
**Enunciado:** Calcule média salarial por departamento.

In [118]:
# Sua solução aqui
df.groupby('departamento')['vendas'].mean()

departamento
Financeiro    261444.222222
Marketing     225893.238636
Operações     250792.024390
RH            235799.279070
TI            250228.033333
Vendas        232101.554217
Name: vendas, dtype: float64

### Exercício 33
**Enunciado:** Conte funcionários por cidade.

In [119]:
# Sua solução aqui
df.groupby('cidade')['nome'].count()

cidade
BeloHorizonte    66
Brasília         51
Curitiba         77
Fortaleza        74
Recife           59
RiodeJaneiro     47
Salvador         63
SãoPaulo         73
Name: nome, dtype: int64

### Exercício 35
**Enunciado:** Agrupe por duas colunas.

In [ ]:
# Sua solução aqui
df.groupby(['cidade', 'departamento'])['nome'].count()

cidade         departamento
BeloHorizonte  Financeiro      11
               Marketing       11
               Operações       12
               RH              11
               TI              13
               Vendas           8
Brasília       Financeiro       7
               Marketing       11
               Operações        5
               RH              10
               TI              10
               Vendas           8
Curitiba       Financeiro      15
               Marketing       13
               Operações       16
               RH              10
               TI              11
               Vendas          12
Fortaleza      Financeiro      14
               Marketing       10
               Operações       14
               RH              13
               TI              10
               Vendas          13
Recife         Financeiro      10
               Marketing        9
               Operações       10
               RH              10
               TI              12
               Vendas           8
RiodeJaneiro   Financeiro       8
               Marketing       13
               Operações        2
               RH               5
               TI              10
               Vendas           9
Salvador       Financeiro       7
               Marketing        9
               Operações       14
               RH              12
               TI              12
               Vendas           9
SãoPaulo       Financeiro       9
               Marketing       12
               Operações        9
               RH              15
               TI              12
               Vendas          16
Name: nome, dtype: int64

### Exercício 36
**Enunciado:** Use value_counts em uma coluna.

In [123]:
# Sua solução aqui
df.departamento.value_counts()

departamento
TI            90
Marketing     88
RH            86
Vendas        83
Operações     82
Financeiro    81
Name: count, dtype: int64

### Exercício 37
**Enunciado:** Crie uma tabela dinâmica.

In [126]:
tabela = pd.pivot_table(
    df,
    values='vendas',
    index='departamento',
    aggfunc=['sum', 'mean', 'count']
)

print(tabela)

                   sum           mean  count
                vendas         vendas vendas
departamento
Financeiro    21176982  261444.222222     81
Marketing     19878605  225893.238636     88
Operações     20564946  250792.024390     82
RH            20278738  235799.279070     86
TI            22520523  250228.033333     90
Vendas        19264429  232101.554217     83